version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./eqori.db
      - SECRET_KEY=your-production-secret-key-change-this
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./backend/eqori.db:/app/eqori.db
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    restart: unless-stopped